version: '3.8'

services:
  plex:
    image: linuxserver/plex
    restart: unless-stopped
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    volumes:
      - .plex/tv:/tv
      - .plex/movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${TOKEN}
  samba:
    image: dperson/samba
    restart: unless-stopped
    environment:
      TZ: 'Europe/Prague'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./plex:/mnt:z
    command: '-s "Plex;/mnt" -p'
